In [1]:
import pandas as pd

In [2]:
data_path = 'datas/beijing_tianqi/beijing_tianqi_2018.csv'

In [3]:
df = pd.read_csv(data_path)

In [4]:
df

          ymd bwendu ywendu tianqi fengxiang fengli  aqi aqiinfo  aqiLevel
0  2018-01-01     3C    -6C     多云       东北风   1-2级   59       良         2
1  2018-01-02     4C    -6C     多云       东北风   3-4级   60       良         2
2  2018-01-03     5C    -6C     多云       东北风   5-6级   61       良         2

In [5]:
df.loc[:,'bwendu'] = df['bwendu'].str.replace('C','').astype('int32')
df.loc[:,'ywendu'] = df['ywendu'].str.replace('C','').astype('int32')

In [6]:
df.head()

          ymd  bwendu  ywendu tianqi fengxiang fengli  aqi aqiinfo  aqiLevel
0  2018-01-01       3      -6     多云       东北风   1-2级   59       良         2
1  2018-01-02       4      -6     多云       东北风   3-4级   60       良         2
2  2018-01-03       5      -6     多云       东北风   5-6级   61       良         2

In [7]:
df.loc[:,'wencha'] = df['bwendu'] - df['ywendu']

In [8]:
df.head()

,ymd,bwendu,ywendu,tianqi,fengxiang,fengli,aqi,aqiinfo,aqiLevel,wencha
0,2018-01-01,3,-6,多云,东北风,1-2级,59,良,2,9
1,2018-01-02,4,-6,多云,东北风,3-4级,60,良,2,10
2,2018-01-03,5,-6,多云,东北风,5-6级,61,良,2,11

In [9]:
df['wencha2'] = df['bwendu'] - df['ywendu']

In [10]:
df.head()

,ymd,bwendu,ywendu,tianqi,fengxiang,fengli,aqi,aqiinfo,aqiLevel,wencha,wencha2
0,2018-01-01,3,-6,多云,东北风,1-2级,59,良,2,9,9
1,2018-01-02,4,-6,多云,东北风,3-4级,60,良,2,10,10
2,2018-01-03,5,-6,多云,东北风,5-6级,61,良,2,11,11

In [11]:
def get_wendu_type(x):
    if x['bwendu'] >=4:
        return 'high temp'
    if x['ywendu'] <=-6:
        return 'low temp'
    return 'normal temp'

In [12]:
df['wendu_type'] = df.apply(get_wendu_type, axis=1)

In [13]:
df.head()

,ymd,bwendu,ywendu,tianqi,fengxiang,fengli,aqi,aqiinfo,aqiLevel,wencha,wencha2,wendu_type
0,2018-01-01,3,-6,多云,东北风,1-2级,59,良,2,9,9,low temp
1,2018-01-02,4,-6,多云,东北风,3-4级,60,良,2,10,10,high temp
2,2018-01-03,5,-6,多云,东北风,5-6级,61,良,2,11,11,high temp

In [14]:
df['wendu_type'].value_counts()

high temp    2
low temp     1
Name: wendu_type, dtype: int64

In [15]:
df.assign(
    ywendu_huashi = lambda x:x['ywendu'] * 9 + 2,
    bwendu_huashi = lambda x:x['bwendu'] * 9 + 2
)

,ymd,bwendu,ywendu,tianqi,fengxiang,fengli,aqi,aqiinfo,aqiLevel,wencha,wencha2,wendu_type,bwendu_huashi,ywendu_huashi
0,2018-01-01,3,-6,多云,东北风,1-2级,59,良,2,9,9,low temp,29,-52
1,2018-01-02,4,-6,多云,东北风,3-4级,60,良,2,10,10,high temp,38,-52
2,2018-01-03,5,-6,多云,东北风,5-6级,61,良,2,11,11,high temp,47,-52

In [16]:
df['wencha_type2'] = '温差正常'
df.loc[df['bwendu']-df['ywendu']>=11, 'wencha_type2'] = '温差大'
df.loc[df['bwendu']-df['ywendu']<=9, 'wencha_type2'] = '温差小'

In [17]:
df.head()

,ymd,bwendu,ywendu,tianqi,fengxiang,fengli,aqi,aqiinfo,aqiLevel,wencha,wencha2,wendu_type,wencha_type2
0,2018-01-01,3,-6,多云,东北风,1-2级,59,良,2,9,9,low temp,温差小
1,2018-01-02,4,-6,多云,东北风,3-4级,60,良,2,10,10,high temp,温差正常
2,2018-01-03,5,-6,多云,东北风,5-6级,61,良,2,11,11,high temp,温差大

In [18]:
df['wencha_type2'].value_counts()

温差小     1
温差大     1
温差正常    1
Name: wencha_type2, dtype: int64

In [19]:
def get_wencha_type3(x):
    if x['bwendu']-x['ywendu']>=11:
        return '温差大'
    if x['bwendu']-x['ywendu']<=9:
        return '温差小'
    return '温差正常'
df['wencha_type3'] = df.apply(get_wencha_type3, axis=1)

In [20]:
df.head()

,ymd,bwendu,ywendu,tianqi,fengxiang,fengli,aqi,aqiinfo,aqiLevel,wencha,wencha2,wendu_type,wencha_type2,wencha_type3
0,2018-01-01,3,-6,多云,东北风,1-2级,59,良,2,9,9,low temp,温差小,温差小
1,2018-01-02,4,-6,多云,东北风,3-4级,60,良,2,10,10,high temp,温差正常,温差正常
2,2018-01-03,5,-6,多云,东北风,5-6级,61,良,2,11,11,high temp,温差大,温差大